"""create_users_table

Revision ID: b1eb0a886b15
Revises: None
Create Date: 2026-07-21 15:06:46.007631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1eb0a886b15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique user ID (64-bit BigInteger)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique user email for authentication'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Argon2id/Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full legal name"),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'RESEARCHER', 'ADMIN', name='userrole', native_enum=False, length=50), nullable=False, comment='User role (patient, doctor, researcher, admin)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status for soft disabling'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email/identity verification flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
