export { PatientSummaryCard } from './PatientSummaryCard';
export type { PatientSummaryData } from './PatientSummaryCard';
export { MedicalRecordPreview } from './MedicalRecordPreview';
export type { MedicalRecordItem } from './MedicalRecordPreview';
export { AiPredictionSummary } from './AiPredictionSummary';
export { MedicineCard } from './MedicineCard';
export type { MedicineItem, MedicineCardProps } from './MedicineCard';
export { PrescriptionBuilder } from './PrescriptionBuilder';
export type { PrescriptionBuilderProps } from './PrescriptionBuilder';
export { LabRecommendationCard } from './LabRecommendationCard';
export type { LabRecommendationCardProps } from './LabRecommendationCard';
export { ConsultationSummaryModal } from './ConsultationSummaryModal';
export type { ConsultationSummaryModalProps } from './ConsultationSummaryModal';
